# Usa a imagem oficial do PHP 8.3.2 com Apache
FROM php:8.3.2-apache

# Instala as dependências necessárias
RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    libzip-dev \
    libpq-dev \ 
    && docker-php-ext-install pdo pdo_pgsql pgsql


# Instala o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Habilita o mod_rewrite para o Apache
RUN a2enmod rewrite

# Define o diretório de trabalho no container
WORKDIR /var/www/html

# Expõe a porta 80
EXPOSE 80
