# Usa a imagem oficial do PHP 8.3.2 com Apache
FROM php:8.3.2-apache

# Instala as dependências necessárias
RUN apt-get update && apt-get install -y git zip unzip libzip-dev && \
    docker-php-ext-install pdo pdo_mysql mysqli

# Instala o Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Habilita o mod_rewrite para o Apache
RUN a2enmod rewrite

# Instala o PHPUnit globalmente usando o Composer
RUN composer global require phpunit/phpunit ^9.5

# Adiciona o diretório global do Composer bin ao PATH
ENV PATH="${PATH}:/root/.composer/vendor/bin"

# Define o diretório de trabalho no container
WORKDIR /var/www/html

# Expõe a porta 80
EXPOSE 80
