version: '3.8'
services:
  php:
    build: ./php
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/projeto
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dadosfuncionarios
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - ./dados:/var/lib/postgresql/data
      - ./postgresql/setup.sql:/docker-entrypoint-initdb.d/setup.sql

