version: '3.8'
services:
  php:
    build: ./php
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: nome_do_banco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    volumes:
      - ./dados:/var/lib/postgresql/data
      - ./postgresql/setup.sql:/docker-entrypoint-initdb.d/setup.sql

